%Index
%Section 1: histogram preparation
%Section 2: polar plot preparation



%
%%Section 1
%

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:%
%    Workbook: Data file S1.xlsx
%    Worksheet: Fig.2%

path=".......\Data file S1.xlsx" %obtain xslx file from supplementary material and enter path here

%% Import data % Auto-generated by MATLAB
opts = spreadsheetImportOptions("NumVariables", 5);
opts.Sheet = "Fig.3";
opts.DataRange = "C41:G46";

% Specify column names and types
opts.VariableNames = ["Healthy", "Spontaneous", "Min", "Mid", "Max"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
StepHeight = readtable(path, opts, "UseExcel", false);

% Clear temporary variables
clear opts

%% display amplitude modulation histogram
figure
hold on
together=StepHeight{:,:}; %single datapoints
n_cond=size(StepHeight,2);
n_subj=size(StepHeight,1);
v1=zeros(1,n_cond); %averages
s1=zeros(1,n_cond); %SEM

%collect mean and SEM for each condition
for ns_i=1:n_cond
    v1(ns_i)= mean(StepHeight{:,ns_i});
    s1(ns_i)= std(StepHeight{:,ns_i})/sqrt(n_subj);
end

%display bar plot
bar(1:n_cond,v1)
errorbar(1:n_cond,v1,s1,'k')
plot(together','ko-')
title('step height (cm)')




%
%%Section 2
%

%% Import data % Auto-generated by MATLAB
opts = spreadsheetImportOptions("NumVariables", 12);
opts.Sheet = "Fig.3";
opts.DataRange = "C14:N19";

% Specify column names and types
opts.VariableNames = ["ph1","ph2", "ph3", "ph4","ph5","void","ph6", "ph7", "ph8","ph9","ph10", "ph11",];
opts.SelectedVariableNames = ["ph1","ph2", "ph3", "ph4","ph5","ph6", "ph7", "ph8","ph9","ph10", "ph11",];
opts.VariableTypes = ["double","double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
StepHeight = readtable("C:\Users\Usagers\Dropbox\writing_CS\Figures\Data file S1.xlsx", opts, "UseExcel", false);

% Clear temporary variables
clear opts


%% display amplitude modulation polar plot
n_cond=size(StepHeight,2);
n_subj=size(StepHeight,1);
SHm=nanmean(StepHeight{:,:});  %averages
SHd=nanstd(StepHeight{:,:})/sqrt(n_cond); %SEM
extraturn= 2*pi-4.5/n_cond*2*pi; %setting the right phase to the polar plot

% smooth
perctosmooth=[SHm';SHm';SHm']; %using padding (circular data)
percsmoothed=smooth(perctosmooth,2);
perc=percsmoothed(end/3+1:end/3*2); %smoothed average
perc2=SHm'+SHd'; %average + SEM

%display polar plot
figure
polarplot(2*pi/n_cond*(0:n_cond)+extraturn,[perc; perc(1)])
hold on
polarplot(2*pi/n_cond*(0:n_cond)+extraturn,[perc2; perc2(1)])
title('step height (cm)')
rlim([0.3 1.7])
